CREATE TABLE IF NOT EXISTS Genre
(
    Genre_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name     varchar(50) NOT NULL,
    CONSTRAINT unqGenre UNIQUE (Name)
);

CREATE TABLE IF NOT EXISTS MPA_Rating
(
    Mpa_ID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Short_Name  varchar(10)  NOT NULL,
    CONSTRAINT unqMPA UNIQUE (Short_Name)
);

CREATE TABLE IF NOT EXISTS Films
(
    Film_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name         varchar(200) NOT NULL,
    Description  varchar(200) NOT NULL,
    Release_Date date,
    Duration     INTEGER,
    Mpa_ID       INTEGER REFERENCES MPA_Rating (Mpa_ID)
);

CREATE TABLE IF NOT EXISTS Users
(
    User_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Login      varchar(50)  NOT NULL,
    Name       varchar(100) NOT NULL,
    Email      varchar(50)  NOT NULL,
    Birth_Date date,
    CONSTRAINT unqUsers UNIQUE (User_ID, Login)
);

CREATE TABLE IF NOT EXISTS Film_Genre
(
    Film_ID  BIGINT REFERENCES Films (Film_ID),
    Genre_ID INTEGER REFERENCES Genre (Genre_ID)
);

CREATE TABLE IF NOT EXISTS Film_User_Likes
(
    Film_ID BIGINT REFERENCES Films (Film_ID),
    User_ID BIGINT REFERENCES Users (User_ID)
);

CREATE TABLE IF NOT EXISTS Friendship
(
    User_ID   BIGINT REFERENCES Users (User_ID),
    Friend_ID BIGINT,
    Approval  boolean
);